spring:
  datasource:
    url: jdbc:h2:mem:login-api-db
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  h2:
    console:
      enabled: true
      path: /h2

      settings:
        trace: false
#        web-allow-others: false


